import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Feed } from "../components/Feed";
import withAuth from "../hoc/withAuth";

const Home: NextPage = (props) => {
  const { setShowAuthModal, session } = props;
  return (
    <>
      <Head>
        <title>art-tok</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col ">
        <Feed setShowAuthModal={setShowAuthModal} session={session} />
      </main>
    </>
  );
};

export default withAuth(Home);
